# This is a basic workflow to help you get started with Actions

name: Blob storage website CI

# Controls when the action will run. 
on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
        
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:            
    - uses: actions/checkout@v2      
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - run: npm run build
    - name: Share artifact inside workflow
      uses: actions/upload-artifact@v1
      with:
          name: react-github-actions-build
          path: build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}  
    - name: Get Artifact
      uses: actions/download-artifact@v1
      with:
        name: react-github-actions-build
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
            az storage blob upload-batch --account-name rkpomodoro -d '$web' -s ./dist
    - name: logout
      run: |
            az logout
